### ISSUE TITLE
Document Usage

### ISSUE THREAD

**Issue by fallsimply** [fallsimply/themer#2]
# sample
``` js
Window.Themer = new Themer()
```
``` css
:root { 
    background: #fff;
    color: #000;
}
:root[dark] {
    background: #000;
    color: #fff;
}
```
